spring.application.name=demo
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username= postgres
spring.datasource.password=

spring.ai.vectorstore.pinecone.api-key=pcsk_6Cd7SR_DvYGvKARiWruuRcZSw16ktrdDzWU4mZrSnE8uQzuxbuQxtLoMwq9SBYbpzQwQVg
spring.ai.vectorstore.pinecone.environment=us-west1-gcp
spring.ai.vectorstore.pinecone.index-name=my-index